mcom_website/urls.py
from django.contrib import admin
from django.urls import path,include
from trend import views
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [

    path('admin/', admin.site.urls),
    path('',views.index,name="main"),
    path('trend/', include("trend.urls")),
    path('accounts/', include("accounts.urls")),
   


]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

trend/urls.py
from django.contrib import admin
from django.urls import path,include
from trend import views
urlpatterns = [
   
    path("upload_dpr/",views.dpr_key_upload, name="dpr_upload"),
    path("dpr_site_list/",views.dpr_site_list, name="dpr_update"),
    path("single_site_view/<str:pk>/",views.single_site_view, name="single_site_view"),
    path("soft_at_update/<str:pk>/<str:at_status>",views.soft_at_update, name="soft_at_update"),
    path("physical_at_update/<str:pk>/<str:at_status>",views.physical_at_update, name="physical_at_update"),
    path("performance_at_update/<str:pk>/<str:at_status>/<str:band>",views.performance_at_update, name="performance_at_update"),
    path("dashboard/",views.all_dashboard, name="dashboard"),
    path("dpr_view/<str:circle>",views.dpr_view, name="dpr_view"),
    path("circle_wise_dashboard/",views.circle_wise_dashboard, name="circle_wise_dashboard"),
    path("circle_wise_dpr_upload/",views.circle_wise_dpr_upload, name="circle_wise_dpr_upload"),
    path("mapa_status_upld/",views.mapa_status_upld, name="mapa_status_upld"),
    path("performance_at_tat_date/<str:pk>",views.performance_at_tat_date, name="performance_at_tat_date"),
    path("mapa_single_site_update/<str:pk>",views.mapa_single_site_update, name="mapa_single_site_update"),
    


]

trend/models.py
from django.db import models
from django.core.validators import MinValueValidator,MaxValueValidator
import datetime 

# 


# Create your models here.
class DPR_table1(models.Model):
    id=models.CharField(max_length = 100,primary_key=True)
    SITE_ID=models.CharField(max_length = 100)
    CIRCLE=models.CharField(max_length = 100)
    Unique_SITE_ID=models.CharField(max_length = 100)
    BAND=models.CharField(max_length = 100)
    TOCO_NAME=models.CharField(max_length=255)
    OA_COMMERCIAL_TRAFFIC_PUT_ON_AIR_MS1_DATE=models.CharField(max_length = 100)
    Project =models.CharField(max_length = 100)
    Activity=models.CharField(max_length = 100)
    # uploaded_date= models.DateTimeField( auto_now_add=True)
   
    Soft_AT_Status=models.CharField(max_length=100,null=True,blank=True)

    SOFT_AT_ACCEPTANCE_DATE=models.DateField(null=True,blank=True,validators=[MaxValueValidator(datetime.date.today())])
    SOFT_AT_ACCEPTANCE_MAIL=models.FileField(upload_to="dpr/dpr_acceptance_mail/soft_at/",null=True,blank=True)
    
    SOFT_AT_REJECTION_DATE=models.DateField(null=True,blank=True,validators=[MaxValueValidator(datetime.date.today())])
    SOFT_AT_REJECTION_REASON=models.TextField(max_length=100,null=True,blank=True)
    # SOFT_AT_REJECTED_TAT_DATE=models.DateField(null=True,blank=True,validators=[MaxValueValidator(datetime.date.today())])
    
    SOFT_AT_OFFERED_DATE=models.DateField(null=True,blank=True,validators=[MaxValueValidator(datetime.date.today())])
    SOFT_AT_OFFERED_REMARKS=models.TextField(max_length=100,null=True,blank=True)
    
    SOFT_AT_PENDING_REASON=models.TextField(max_length=100,null=True,blank=True)
    SOFT_AT_PENDING_REMARK=models.TextField(max_length=100,null=True,blank=True)
    SOFT_AT_PENDING_TAT_DATE=models.DateField(null=True,blank=True,validators=[MaxValueValidator(datetime.date.today())])
    
    PHYSICAL_AT_Status=models.CharField(max_length=100,null=True,blank=True)
    
    PHYSICAL_AT_ACCEPTANCE_DATE=models.DateField(null=True,blank=True,validators=[MaxValueValidator(datetime.date.today())])
    PHYSICAL_AT_ACCEPTANCE_MAIL=models.FileField(upload_to="dpr/dpr_acceptance_mail/physical_at/",null=True,blank=True)
    
    PHYSICAL_AT_REJECTION_DATE=models.DateField(null=True,blank=True,validators=[MaxValueValidator(datetime.date.today())])
    PHYSICAL_AT_REJECTION_REASON=models.TextField(max_length=100,null=True,blank=True)
    # PHYSICAL_AT_REJECTED_TAT_DATE=models.DateField(null=True,blank=True,validators=[MaxValueValidator(datetime.date.today())])
    
    PHYSICAL_AT_OFFERED_DATE=models.DateField(null=True,blank=True,validators=[MaxValueValidator(datetime.date.today())])
    PHYSICAL_AT_OFFERED_REMARKS=models.TextField(max_length=100,null=True,blank=True)
    
    PHYSICAL_AT_PENDING_REASON=models.TextField(max_length=100,null=True,blank=True)
    PHYSICAL_AT_PENDING_REMARK=models.TextField(max_length=100,null=True,blank=True)
    PHYSICAL_AT_PENDING_TAT_DATE=models.DateField(null=True,blank=True,validators=[MaxValueValidator(datetime.date.today())])
    



    Performance_AT_Status=models.CharField(max_length=100,null=True,blank=True)
    
    
    PERFORMANCE_AT_ACCEPTANCE_DATE=models.DateField(null=True,blank=True,validators=[MaxValueValidator(datetime.date.today())])
    # PERFORMANCE_AT_ACCEPTANCE_MAIL=models.FileField(upload_to="dpr/dpr_acceptance_mail/performance_at/",null=True,blank=True)
    
    PERFORMANCE_AT_REJECTION_DATE=models.DateField(null=True,blank=True,validators=[MaxValueValidator(datetime.date.today())])
    PERFORMANCE_AT_REJECTION_REASON=models.TextField(max_length=100,null=True,blank=True)
    # PERFORMANCE_AT_REJECTED_TAT_DATE=models.DateField(null=True,blank=True)
    
    PERFORMANCE_AT_OFFERED_DATE=models.DateField(null=True,blank=True,validators=[MaxValueValidator(datetime.date.today())])
    PERFORMANCE_AT_OFFERED_REMARKS=models.TextField(max_length=100,null=True,blank=True)
    
    PERFORMANCE_AT_PENDING_REASON=models.TextField(max_length=100,null=True,blank=True)
    PERFORMANCE_AT_PENDING_REMARK=models.TextField(max_length=100,null=True,blank=True)
    PERFORMANCE_AT_PENDING_TAT_DATE=models.DateField(null=True,blank=True,validators=[MaxValueValidator(datetime.date.today())])

    MAPA_STATUS=models.CharField(max_length=100,null=True,blank=True,default="NOT OK")
    
    def __str__ ( self ) :
        return str(self.SITE_ID)
   
class DPR_file(models.Model):
   
    dpr_file=models.FileField(upload_to="dpr_files/")
    uploaded_date= models.DateTimeField( auto_now_add=True)
    
    def __str__ ( self ) :
        return str(self.dpr_file)


class DPR_update_status(models.Model):
   

    id=models.CharField(max_length = 100,primary_key=True)
    SITE_ID = models.CharField(max_length = 100)
    update_status=models.CharField(max_length=100,null=True,blank=True)
    Remark=models.TextField(max_length=100,null=True,blank=True)

    
    def __str__ ( self ):
        return str(self.SITE_ID)

class performance_at_table(models.Model):

    key= models.ForeignKey(DPR_table1, max_length = 100, on_delete=models.CASCADE)
    band=models.CharField(max_length=100,blank=True)
    Performance_AT_Status=models.CharField(max_length=100,blank=True)
    PERFORMANCE_AT_ACCEPTANCE_DATE=models.DateField(null=True,blank=True,validators=[MaxValueValidator(datetime.date.today())])
    
    PERFORMANCE_AT_ACCEPTANCE_MAIL=models.FileField(upload_to="dpr/dpr_acceptance_mail/performance_at/",null=True,blank=True)
   
    PERFORMANCE_AT_REJECTION_DATE=models.DateField(null=True,blank=True,validators=[MaxValueValidator(datetime.date.today())])
    PERFORMANCE_AT_REJECTION_REASON=models.TextField(max_length=100,null=True,blank=True)
    # PERFORMANCE_AT_REJECTED_TAT_DATE=models.DateField(null=True,blank=True)

    PERFORMANCE_AT_OFFERED_DATE=models.DateField(null=True,blank=True,validators=[MaxValueValidator(datetime.date.today())])
    PERFORMANCE_AT_OFFERED_REMARKS=models.TextField(max_length=100,null=True,blank=True)

    PERFORMANCE_AT_PENDING_REASON=models.TextField(max_length=100,null=True,blank=True)
    PERFORMANCE_AT_PENDING_REMARK=models.TextField(max_length=100,null=True,blank=True)
    # PERFORMANCE_AT_PENDING_TAT_DATE=models.DateField(null=True,blank=True,validators=[MaxValueValidator(datetime.date.today())])
    # overall
    def __str__ ( self ) :
        return  str(self.band)

templates/trend/DPR_dashboard.html
{% extends "trend/base.html" %}
{% load static %}
{% block title%}Add category item{% endblock title%}
{% block css %}
<link rel="stylesheet" href="{% static 'css/trend/DPR_dashboard.css' %}" /> {% endblock css%}
{% block content%}

<div class="main-body">
    <div class="">
        <h2 style="text-align: center;">DASHBOARD</h2>
    </div>
    <div class="das-body">

        <div class="soft_at das-box">

            <h3 style="text-align: center;">Total Soft AT Done</h3>
            <div class="data">
                <div class="total">
                    <div class="inner">
                        <h1>{{total_soft_at_done}}</h1>
                    </div>
                </div>
                <br>
               <div  class="percent">Percentage: {{percent_soft_at_done}}%</div>
               <div  class="percent"> Total Ms1 Site: {{total_no_site}}</div>
               <div  class="percent"> Total Ms2 Site: {{Ms2_site}}</div>
               <!-- <div  class="percent"> Percentage Ms2 Site: {{percent_ms2_site}}</div> -->
               <div  class="percent"> Total MAPA: {{total_mapa}}</div>
               {% if percent_ms2_site >= 90 %}
               <div  class="percent"  style="color: greenyellow;"> Percentage Ms2 Site: {{percent_ms2_site}}%</div>
               
               {% endif %}

               {% if percent_ms2_site < 90 and percent_ms2_site >= 80 %}
               <div  class="percent"  style="color:  yellow;"> Percentage Ms2 Site: {{percent_ms2_site}}%</div>
            
               {% endif %}

               {% if percent_ms2_site < 80 %}
               <div  class="percent"  style="color: rgb(255, 92, 47);"> Percentage Ms2 Site: {{percent_ms2_site}}%</div>
               
               {% endif %}
            </div>
        </div>
        <div class="physical_at das-box">

            <h3 style="text-align: center;">Total Physical AT Done</h3>
            <div class="data">
                <div class="total">
                    <div class="inner">

                        <h1>{{total_physical_at_done}}</h1>
                    </div>
                </div>
                <br>
                <div class="percent">Percentage: {{percent_physical_at_done}}%</div>
                <div  class="percent"> Total Ms1 Site: {{total_no_site}}</div>
               <div  class="percent"> Total Ms2 Site: {{Ms2_site}}</div>
               <!-- <div  class="percent"> Percentage Ms2 Site: {{percent_ms2_site}}</div> -->
               <div  class="percent"> Total MAPA: {{total_mapa}}</div>
                            {% if percent_ms2_site >= 90 %}
                            <div  class="percent"  style="color: greenyellow;"> Percentage Ms2 Site: {{percent_ms2_site}}%</div>
                            
                            {% endif %}

                            {% if percent_ms2_site < 90 and percent_ms2_site >= 80 %}
                            <div  class="percent"  style="color:  yellow;"> Percentage Ms2 Site: {{percent_ms2_site}}%</div>
                         
                            {% endif %}

                            {% if percent_ms2_site < 80 %}
                            <div  class="percent"  style="color: rgb(255, 92, 47);"> Percentage Ms2 Site: {{percent_ms2_site}}%</div>
                            
                            {% endif %}
            </div>
        </div>

        <div class="performance_at das-box">

            <h3 style="text-align: center;">Total Performance AT Done</h3>
            <div class="data">
                <div class="total">
                    <div class="inner">
                        <h1>{{total_performance_at_done}}</h1>
                    </div>
                </div>
                <br>
               <div  class="percent"> Percentage: {{percent_performance_at_done}}%</div>
               <div  class="percent"> Total Ms1 Site: {{total_no_site}}</div>
               <div  class="percent"> Total Ms2 Site: {{Ms2_site}}</div>
               <!-- <div  class="percent"> Percentage Ms2 Site: {{percent_ms2_site}}</div> -->
               <div  class="percent"> Total MAPA: {{total_mapa}}</div>
               {% if percent_ms2_site >= 90 %}
               <div  class="percent"  style="color: greenyellow;"> Percentage Ms2 Site: {{percent_ms2_site}}%</div>
               
               {% endif %}

               {% if percent_ms2_site < 90 and percent_ms2_site >= 80 %}
               <div  class="percent"  style="color:  yellow;"> Percentage Ms2 Site: {{percent_ms2_site}}%</div>
            
               {% endif %}

               {% if percent_ms2_site < 80 %}
               <div  class="percent"  style="color: rgb(255, 92, 47);"> Percentage Ms2 Site: {{percent_ms2_site}}%</div>
               
               {% endif %}
                
            </div>
        </div>

    </div>

    <!-- <div class="">
        <p>Total Ms1 Site: {{total_no_site}}</p>
    </div>
    <div class="">
        <p>Total Ms2 Site: {{Ms2_site}}</p>
    </div> -->
</div>
<div class="only_status main-body" style="margin-top: 30px; margin-bottom: 30px;">


    <div class="">
        <h2 style="text-align: center;">ONLY STATUS</h2>
    </div>
    <div class="das-body">

        <div class="soft_at das-box">

            <h3 style="text-align: center;">Only Soft AT Done</h3>
            <div class="data">
                <div class="total">
                    <div class="inner">
                        <h1>{{total_soft_at_done}}</h1>
                    </div>
                </div>
               
            </div>
        </div>
        <div class="physical_at das-box">

            <h3 style="text-align: center;">Only Physical AT Done</h3>
            <div class="data">
                <div class="total">
                    <div class="inner">

                        <h1>{{total_physical_at_done}}</h1>
                    </div>
                </div>
                
            </div>
        </div>

        <div class="performance_at das-box">

            <h3 style="text-align: center;">Only Performance AT Done</h3>
            <div class="data">
                <div class="total">
                    <div class="inner">
                        <h1>{{total_performance_at_done}}</h1>
                    </div>
                </div>
                
                
            </div>
        </div>

    </div>

    <!-- <div class="">
        <p>Total Ms1 Site: {{total_no_site}}</p>
    </div>
    <div class="">
        <p>Total Ms2 Site: {{Ms2_site}}</p>
    </div> -->
</div>
</div>

{% endblock content%}

templates/trend/DPR_site_list.html
{% extends 'trend/base.html'%}
{% load static %}
{% block css%}
<link rel="stylesheet" href="{% static 'css/trend/DPR_site_list.css' %}" /> {% endblock %}
{% block title %} catagory:{{c_head}} {% endblock title %}

{% block content %}

<div id="body_content">
  <div id="bck_add_btn">

    <!-- <a href="#" ><button type="submit" class="btn"  id="back_button">Back</button></a> -->
    <div id="search-box">
      <form class="form">
        {% csrf_token %}
        <input type="text" placeholder="Search By Circle" name="circle search" id="user" required />
        <button type="Submit" value="Search" id="search-button" class="btn">
          <i class="fa fa-search"></i></button>
      </form>


      <!-- <a href="#">  <button type = " submit " id='add_products' class="btn" >Default</button ></a> -->
    </div>

    <div id="search-box">
      <form class="form">
        {% csrf_token %}
        <input type="text" placeholder="Search By Site ID" name="id search" id="user" required />
        <button type="Submit" value="Search" id="search-button" class="btn">
          <i class="fa fa-search"></i></button>
      </form>


      <!-- <a href="#">  <button type = " submit " id='add_products' class="btn" >Default</button ></a> -->
    </div>
    <div id="search-box">
      <form class="form">
        {% csrf_token %}
        <input type="text" placeholder="Search By Project" name="project search" id="user" required />
        <button type="Submit" value="Search" id="search-button" class="btn">
          <i class="fa fa-search"></i></button>
      </form>


      <!-- <a href="#">  <button type = " submit " id='add_products' class="btn" >Default</button ></a> -->
    </div>


    <div id="search-box">
      <form class="form">
        {% csrf_token %}
        <input type="text" placeholder="Search By activity" name="activity search" id="user" required />
        <button type="Submit" value="Search" id="search-button" class="btn">
          <i class="fa fa-search"></i></button>
      </form>


      <!-- <a href="#">  <button type = " submit " id='add_products' class="btn" >Default</button ></a> -->
    </div>



  </div>
 
  <div id="cat_wise_item_table">
    <table class="table" id="table">
      <thead>
        <tr>
          <th style="width:5%">S/NO.</th>
          <th>CIRCLE</th>
          <th>SITE ID<a href="?short=item_name" style="text-decoration:none;"> <span> &#8593; </span> </a> <a
              href="?short=-item_name" style="text-decoration:none;"> <span> &#8595;</span> </a></th>
          <th>PROJECT</th>
          <th>ACTIVITY</th>
          <th>BAND<a href="?short=short_discription" style="text-decoration:none;"> <span> &#8593; </span> </a> <a
              href="?short=-short_discription" style="text-decoration:none;"> <span> &#8595;</span> </a></th>


          <!-- <th ><h2>Specs</h2></th> -->



          <th> Actions</th>
        </tr>
      </thead>
      
      <tbody>
        
        {% for site in object %}
        <tr>
          <td>{{forloop.counter}}</td>
          <td>{{site.CIRCLE}}</td>
          <td> {{ site.SITE_ID}}</td>
          <td>{{site.Project}}</td>
          <td>{{site.Activity}}</td>
          <td> {{ site.BAND}}</td>




          <td>

            <span style="display: inline-block;">
              <a href="{% url 'single_site_view' site.id  %}"> <button type=" submit " class="btn"
                  id="view">View</button></a>
            </span>

            <!-- {% if perms.shop.change_catlist %}
            <span style="display: inline-block;">
               <a href="#">  <button type = " submit "  class="btn" id="edit" >Edit</button ></a>
              </span>
              {% endif %}

              {% if perms.shop.change_catlist %}
              <span style="display: inline-block;"> 
                <form method = "post" action = "#">
                 {%csrf_token %}
                 <button type = " submit " id='deactivate' class="btn"> Deactivate </button>
                 </form >
              </span>
              {% endif %} -->
          </td>
        </tr>
        <!--    <td > <a href="#" id="dellink">Delete</a> <a href="#" id="uplink">Update</a></td> -->
        {% endfor %}
      </tbody>
     
    </table>
   
  </div>
</div>

{% endblock content %}

templates/trend/DPR_upload.html
{% extends "trend/base.html" %}
{% load static %}
{% block title%}Add category{% endblock title%}
{% block css %} <link rel="stylesheet" href="{% static 'css/trend/DPR_upload.css' %}" />  {% endblock css%}
{% block content%}

<div id="form_body">
  <div id="wrapper_download">
      <a href="/{{path}}"> <button type=" submit " id='Download' class="btn"><i class="fa fa-download"></i>
        Download Template</button>
      </a>
    
  </div>
<form method = "post" enctype = "multipart/form-data" id="form" >
   <h2 style="text-align:center;">Upload DPR Keys</h2>
    {% csrf_token %}
    <label for="myfile">Select a file:</label>
    <input type="file" id="myfile" name="myfile">
    <br>
  <div id="frm_btns"> <button type = "submit" class="btn" id="add">UPLOAD</button>
    <a href="/"> <button id="cancel" class="btn" type="button">Cancel</button ></a>
    </div>
   </form>
     {% for message in messages %}
     
        <h3 class="message" style="text-align:center;">{{message}}</h3>
       
     {% endfor %}

   </div>
  {% endblock content%}

templates/trend/DPR_upload_form.html
{% extends "trend/base.html" %}
{% load static %}
{% block title%}Add category{% endblock title%}
{% block css %} <link rel="stylesheet" href="{% static 'css/trend/DPR_circle_wise_upload.css' %}" />  {% endblock css%}
{% block content%}

<div id="form_body">
  <div id="wrapper_download">
    <a href="/{{path}}"> <button type=" submit " id='Download' class="btn"><i class="fa fa-download"></i>
      Download Template</button>
    </a>
  
</div>

<form method = "post" enctype = "multipart/form-data" id="form" >
    <h2 style="text-align:center;">Upload DPR</h2>
     {% csrf_token %}
     <label for="myfile">Select Dpr file:</label>
     <input type="file" id="myfile" name="myfile" required >
     <br>
     <label for="soft_at">Select Soft AT Acceptance Proof file:</label>
     <input type="file" id="soft_at" name="soft_at" required >
     <br>
     <label for="physical_at">Select Physical AT Acceptance Proof file:</label>
     <input type="file" id="physical_at" name="physical_at" required >
     <br>
     <label>Select Performance AT Acceptance Proof file:</label>
     <br>
 
    
     <label for="G1800">G1800:</label>
     <input type="file" id="G1800" name="G1800">
     <label for="L900">L900:</label>
     <input type="file" id="L900" name="L900">
     <label for="L1800">L1800:</label>
     <input type="file" id="L1800" name="L1800">
     <label for="L2300">L2300:</label>
     <input type="file" id="L2300" name="L2300">
     <label for="L2100">L2100:</label>
     <input type="file" id="L2100" name="L2100">





   <div id="frm_btns"> <button type = "submit" class="btn" id="add">UPLOAD</button>
     <a href="/"> <button id="cancel" class="btn" type="button">Cancel</button ></a>
     </div>
    </form>
      {% for message in messages %}
      
         <h3 class="message" style="text-align:center;">{{message}}</h3>
        
      {% endfor %}
 
    </div>

    

    {% endblock %}

  

templates/trend/MAPA_upload.html
{% extends "trend/base.html" %}
{% load static %}
{% block title%}Add category item{% endblock title%}
{% block css %} <link rel="stylesheet" href="{% static 'css/trend/MAPA_upload.css' %}" />  {% endblock css%}
{% block content%}
<div id="form_body">
<form method = "post" enctype = "multipart/form-data" id="form" >
   <h2 style="text-align:center;">MAPA UPLOAD </h2>
   {% csrf_token %}
    
   <label for="myfile">Select a file:</label>
   <input type="file" id="myfile" name="MAPA_file">
    <br>
    <div id="frm_btns">
   <button type="submit" class="btn" id="add">Submit</button>
   <a href="/"> <button  type="button" id="cancel" class="btn">cancel</button >
   </div>  
</form>

   </div>
   {% for message in messages %}
     
   <h3 class="message" style="text-align:center;">{{message}}</h3>
  
{% endfor %}
    {% endblock content%}

templates/trend/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}BASE{% endblock title %}</title>
  <link rel="stylesheet" href=" {% static '/css/trend/base.css' %}" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

  {% block css%}
  {% endblock %}
</head>

<body>

  <div class="content">
    <div id="logo">
      <img id="icon" src="{% static '/icons/mcom_logo.jpg' %}" alt="Mobilecomm" class="headerimg" />
    </div>
    <h1 id="p1">Mobilecomm Technologies</h1>


  </div>


  <div class="navbar">
    <ul id="nav-btn">
      <li><a class="btn1 active" href="/shop/">Home</a></li>
      <li><a class=" btn1" href="/shop/about/">About Us</a></li>
      <li><a class=" btn1" href="/shop/contactus/">Contact Us</a></li>
      {% if perms.trend.add_dpr_table1 %}

      <li class="dropdown2"><span class="btn1">Upload DPR</span>
        <div class="dashboard-list">
          <a href="{% url 'dpr_upload' %}">DPR Keys</a>
          <a href="{% url 'circle_wise_dpr_upload'  %}">DPR Report</a>
          <a href="{%  url 'mapa_status_upld'  %}">DPR MAPA Status</a>

        </div>

      </li>
      {% endif %}

      {% if perms.trend.view_dpr_table1 %}
      <li><a class=" btn1" href="{% url 'dpr_update'%}">View Site List/Update</a></li>
      {% endif %}

      {% if perms.trend.view_dpr_table1 %}
      <li class="dropdown2"><span class="btn1">DASHBOARD</span>
        <div class="dashboard-list">
          <a href="{% url 'dashboard'  %}">Over All</a>
          <a href="{% url 'circle_wise_dashboard'  %}">Circle-Wise</a>
          <div class="dropdown2-1 project"> <span> Project-Wise</span>
            <div class="Project-list">
              <a href="/trend/circle_wise_dashboard/?project=NT">NT</a>
              <a href="/trend/circle_wise_dashboard/?project=ULS">ULS</a>
              <a href="/trend/circle_wise_dashboard/?project=Capacity Upgrade">Capacity Upgrade</a>
              <a href="/trend/circle_wise_dashboard/?project=Relocation">Relocation</a>
            </div>
          </div>
        </div>
      </li>
      {% endif %}

      {% if perms.trend.view_dpr_table1 %}
      <li class="dropdown1"><span class="btn1">View DPR</span>
        <div class="circle-list">
          <a href="{% url 'dpr_view' 'ALL'  %}">ALL</a>
          <!-- <a href="{% url 'dpr_view' 'MUM'  %}">MUM</a>
          <a href="{% url 'dpr_view' 'TNCH'  %}">TNCH</a>
          <a href="{% url 'dpr_view' 'AP'  %}">AP</a>
          <a href="{% url 'dpr_view' 'Delhi'  %}">Delhi</a> -->
          {% for c in cir %}
         
          {% endfor %}
        </div>

      </li>
      {% endif %}


    </ul>

    <div class="lginout" id="lginout">
      {% if user.is_authenticated %}

      <!-- <div id="pro_image" onclick="menuToggle();">
          {% if request.user.profile.pro_pic %}
          <img src="{{request.user.profile.pro_pic.url}}" height="30" width="30"/>
          {%  endif %}
        </div> -->

      <!-- <div class="menu">
          <ul>
            <li><a href="#">Change Profile</a></li><hr style="margin:1;">
            <li><a href="#">Change Password</a></li>
          </ul>
         </div> -->
      <ul class="header_user_name">

        <li>
          <p id="name" style="text-transform: capitalize;">{{request.session.uname}}</p>
        </li>
        <li>
          <button class="lgout"><a style="text-decoration:none; color:black;" class="ac"
              href="{% url 'logout'  %}">logout</a></button>
        </li>
      </ul>
      {% else %}
      <ul class="header_user_name">
        <li>
          <button class="lgin"><a class="ac" style="text-decoration:none; color:black;"
              href="{% url 'login' %}">login</a></button>
        </li>
        <!-- <li>
              <button class="reg"><a class="ac" style="text-decoration:none; color:black;" href="/shop_accounts/register/"
                >register</a></button>
              
            </li> -->
      </ul>
      {% endif %}
    </div>

    </ul>
  </div>

  </div>

  <!-- print(user.has_perm("blog.delete_post")) # => False
print(user.has_perm("blog.change_post")) # => False
print(user.has_perm("blog.view_post")) # => True
print(user.has_perm("blog.add_post")) # => True -->



  <div class="body">
    {% block content %}

    {% endblock %}
  </div>
  <script>

    function menuToggle() {
      const toggleMenu = document.querySelector('.menu');
      toggleMenu.classList.toggle('active')
    }





  </script>

</body>


</html>